--CREATE tablespace MERCORACLE datafile 'mercoracle.dbf' size 10M autoextend on;
--
--
--create user MERCORACLE identified by MERCORACLE
--default tablespace MERCORACLE
--quota 1M on MERCORACLE;
grant connect to mercoracle;


-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1536
--   at:        2019-03-10 11:17:07 CET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



CREATE TABLE mercoracle.employee_category (
    codigo         NUMBER(2) NOT NULL,
    salario_base   NUMBER(12, 2) NOT NULL
);

ALTER TABLE mercoracle.employee_category ADD CONSTRAINT employee_category_pk PRIMARY KEY ( codigo );

CREATE TABLE mercoracle.employees (
    emp_no                     INTEGER NOT NULL,
    birth_date                 DATE NOT NULL,
    salario_especifico         NUMBER(12, 2) NOT NULL,
    first_name                 VARCHAR2(20) NOT NULL,
    last_name                  VARCHAR2(30) NOT NULL,
    gender                     CHAR(1),
    employee_category_codigo   NUMBER(2) NOT NULL
);

ALTER TABLE mercoracle.employees
    ADD CHECK ( gender IN (
        'F',
        'M'
    ) );

ALTER TABLE mercoracle.employees ADD CONSTRAINT employees_pk PRIMARY KEY ( emp_no );

CREATE TABLE mercoracle.equipo (
    codigo                 INTEGER NOT NULL,
    descripcion            VARCHAR2(30) NOT NULL,
    fecha_de_adquisicion   DATE NOT NULL,
    tipo                   VARCHAR2(30) NOT NULL,
    marca                  VARCHAR2(30),
    precio                 NUMBER,
    employees_emp_no       INTEGER NOT NULL
);

ALTER TABLE mercoracle.equipo
    ADD CHECK ( tipo IN (
        'ALMACEN',
        'CAJA REGISTRADORA',
        'CHARCUTERIA',
        'LIMPIEZA'
    ) );

ALTER TABLE mercoracle.equipo ADD CONSTRAINT equipo_pk PRIMARY KEY ( codigo );

CREATE TABLE mercoracle.retencion (
    tipo          NUMBER(2) NOT NULL,
    descripcion   VARCHAR2(256) NOT NULL,
    porcentaje    NUMBER(3, 2)
);

ALTER TABLE mercoracle.retencion ADD CHECK ( porcentaje BETWEEN 0 AND 1 );

ALTER TABLE mercoracle.retencion ADD CONSTRAINT retencion_pk PRIMARY KEY ( tipo );

CREATE TABLE mercoracle.retenciones (
    employee_category_codigo   NUMBER(2) NOT NULL,
    retencion_tipo             NUMBER(2) NOT NULL
);

ALTER TABLE mercoracle.retenciones ADD CONSTRAINT retenciones_pk PRIMARY KEY ( employee_category_codigo,
                                                                             retencion_tipo );

ALTER TABLE mercoracle.employees
    ADD CONSTRAINT employees_employee_category_fk FOREIGN KEY ( employee_category_codigo )
        REFERENCES mercoracle.employee_category ( codigo );

ALTER TABLE mercoracle.equipo
    ADD CONSTRAINT equipo_employees_fk FOREIGN KEY ( employees_emp_no )
        REFERENCES mercoracle.employees ( emp_no );

ALTER TABLE mercoracle.retenciones
    ADD CONSTRAINT ret_employee_category_fk FOREIGN KEY ( employee_category_codigo )
        REFERENCES mercoracle.employee_category ( codigo );

ALTER TABLE mercoracle.retenciones
    ADD CONSTRAINT ret_retencion_fk FOREIGN KEY ( retencion_tipo )
        REFERENCES mercoracle.retencion ( tipo );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

ALTER SYSTEM SET "WALLET_ROOT"='C:\Users\alumnos\Oracle\Wallet' scope=SPFILE; -- primero hay que crearla desde el explorador

show parameters;

ALTER SYSTEM SET TDE_CONFIGURATION="KEYSTORE_CONFIGURATION=FILE" scope=both;

-- ADMINISTER KEY MANAGEMENT CREATE KEYSTORE IDENTIFIED BY password;  -- con sqlplus / as syskm
-- ADMINISTER KEY MANAGEMENT CREATE AUTO_LOGIN KEYSTORE FROM KEYSTORE IDENTIFIED BY bd;
-- ADMINISTER KEY MANAGEMENT SET KEYSTORE open IDENTIFIED BY bd;
-- ADMINISTER KEY MANAGEMENT SET KEY identified by bd with backup;

select * from mercoracle.employees;

alter table mercoracle.employees 
modify first_name VARCHAR2(128) ENCRYPT;

alter table mercoracle.employees 
modify last_name VARCHAR2(128) ENCRYPT;

alter table mercoracle.employees 
modify salario_especifico NUMBER(6) ENCRYPT;

-- 7
select * from DBA_ENCRYPTED_COLUMNS;

-- 8
insert into mercoracle.employee_category (codigo,salario_base)
values ('1','1200');

insert into mercoracle.employee_category (codigo,salario_base)
values ('2','1400');

insert into mercoracle.employees (emp_no, birth_date, Salario_Especifico, first_name, last_name, gender, employee_category_codigo)
values ('1','13/02/1960','1500','Antonio','García','M','1');

insert into mercoracle.employees (emp_no, birth_date, Salario_Especifico, first_name, last_name, gender, employee_category_codigo)
values ('2','19/04/1980','1650','María','Pérez','F','1');

alter system flush buffer_cache;


--C:\Users\alumnos>C:\Users\alumnos\Downloads\Strings\strings64.exe -a C:\Users\alumnos\Oracle_instalacion\database\MERCORACLE.DBF
--
--Strings v2.53 - Search for ANSI and Unicode strings in binary images.
--Copyright (C) 1999-2016 Mark Russinovich
--Sysinternals - www.sysinternals.com
--
--}|{z
--ZORCL
--MERCORACLE
--AAAAAAAA
--AAAAAAAA
--AAAAAAAA
--^gT
--]at`
--Nw~
--m9@
--tv+
--4t;
---]A
--nd5sF
--r+0
--YY2
--OT_ {
--*Nv
--AAAAAAAA

-- No se aprecian los datos descritos en el fichero porque estos están cifrados


-- 9
create or replace function sec_function(mercoracle varchar2, employees varchar2)
  Return varchar2
is
  user VARCHAR2(100);
Begin
if (SYS_CONTEXT('USERENV', 'ISDBA')='TRUE') 
then return ''; -- Si el usuario se conecta como sysdba, podrá ver toda la tabla.
else
  user := SYS_CONTEXT('userenv', 'SESSION_USER');
  return 'UPPER(USER_NAME) = ''' || user || '''';
end if;
End;
/

-- 10
alter table mercoracle.employees add user_name varchar2(25) null;

-- 11
CREATE tablespace prueba_politica datafile 'prueba_politica.dbf' size 10M autoextend on;

create user prueba_politica identified by prueba_politica
default tablespace prueba_politica
quota 1M on prueba_politica;

grant connect to prueba_politica;

BEGIN
DBMS_RLS.ADD_POLICY (
   'MERCORACLE', 'employees', 'emp_policy', 'MERCORACLE', 'SEC_FUNCTION', 'select');
end;
/

begin
DBMS_RLS.ENABLE_POLICY (
   object_schema=>'MERCORACLE',
   object_name=>'EMPLOYEES',
   policy_name=>'EMP_POLICY',
   enable=>true);
end;
/

-- 12
begin
DBMS_RLS.ENABLE_POLICY (
   object_schema=>'MERCORACLE',
   object_name=>'EMPLOYEES',
   policy_name=>'EMP_POLICY',
   enable=>false);
end;
/

-- 13
grant select on mercoracle.employees to prueba_politica;
grant insert on mercoracle.employees to prueba_politica;
grant delete on mercoracle.employees to prueba_politica;
grant update on mercoracle.employees to prueba_politica;

-- 14

