--CHECKS DE PORCENTAJES
ALTER TABLE IVA ADD CONSTRAINT CHECK_PORCENTAJE_IVA CHECK(PORCENTAJE >= 0 AND PORCENTAJE <=100);
ALTER TABLE RETENCIONES ADD CONSTRAINT CHECK_PORCENTAJE_RETEN CHECK(PORCENTAJE >= 0 AND PORCENTAJE <=100);

--CHECKS DE FECHAS
ALTER TABLE HISTORICO_OFERTA ADD CONSTRAINT CHECK_FECHA_FIN CHECK(FECHA_FIN >= FECHA_INICIO); --CAMBIAR REGISTRO 1O, FECHA INCORRECTA

--CHECK DE EMAILS
ALTER TABLE EMPLEADO ADD CONSTRAINT CHECK_EMPLEADO_EMAIL CHECK(EMAIL LIKE '%@%');
ALTER TABLE FIDELIZADO ADD CONSTRAINT CHECK_FIDELIZADO_EMAIL CHECK(EMAIL LIKE '%@%');
ALTER TABLE PROVEEDOR ADD CONSTRAINT CHECK_PROVEEDOR_EMAIL CHECK(EMAIL LIKE '%@%');

--BORRAR UN CHECK: ALTER TABLE table_name DROP CONSTRAINT constraint_name;
