--INDICES DE TABLAS
CREATE INDEX IDX_NOMBRE_CARGO_ ON CAT_EMPLEADO (NOMBRE_CARGO);
CREATE INDEX IDX_COD_POSTAL_CLI ON CLIENTE (CODIGO_POSTAL);
CREATE INDEX IDX_COD_POSTAL_EMP ON EMPLEADO (CODIGO_POSTAL);
CREATE INDEX IDX_ENTREGA_CLIENTE ON ENTREGA (CLIENTE);
CREATE INDEX IDX_MOBILIARIO_PASILLO ON MOBILIARIO (PASILLO);
CREATE INDEX IDX_TIPO_OFERTA ON OFERTA (TIPO_OFERTA);
CREATE INDEX IDX_PRODUCTO_CATEGORIA ON PRODUCTO (CATEGORIA);
CREATE INDEX IDX_RETENCION_NOMBRE ON RETENCION (NOMBRE);
CREATE INDEX IDX_TICKET_FECHA_FIDELIZADO ON TICKET (FECHA_PEDIDO, FIDELIZADO);

--ALTER INDEX index_name RENAME TO new_index_name;
--DROP INDEX index_name;