--TABLA DETALLE
ALTER TABLE DETALLE ADD CONSTRAINT CHECK_LINEA_DETALLE CHECK(LINEA >= 1);

--TABLA FACTURA
ALTER TABLE FACTURA ADD CONSTRAINT CHECK_NUM_FACT CHECK(NUM_FACTURA >= 0);

--TABLA FIDELIZADO
ALTER TABLE FIDELIZADO MODIFY PUNTOS_ACUMULADOS DEFAULT 0; 
ALTER TABLE FIDELIZADO ADD CONSTRAINT CHECK_PUNTOS CHECK(PUNTOS_ACUMULADOS >= 0);

--HISTORICO_PRECIO
ALTER TABLE HISTORICO_PRECIO ADD CONSTRAINT CHECK_PRECIO_HISTORICO CHECK(PRECIO >= 0);

--MOBILIARIO
ALTER TABLE MOBILIARIO ADD CONSTRAINT CHECK_CAP_MOB CHECK(CAPACIDAD >= 1);

--PRODUCTO
ALTER TABLE PRODUCTO ADD CONSTRAINT CHECK_STOCK_PROD CHECK(STOCK >= 0);
ALTER TABLE PRODUCTO ADD CONSTRAINT CHECK_EXPO_PROD CHECK(EXPOSICION >= 0);
ALTER TABLE PRODUCTO ADD CONSTRAINT CHECK_METROS_PROD CHECK(METROS_LINEALES >= 0);
ALTER TABLE PRODUCTO ADD CONSTRAINT CHECK_PRECIO_PROD CHECK(PRECIO_ACTUAL >= 0);

--TICKET
ALTER TABLE TICKET MODIFY PUNTOS DEFAULT 0;
ALTER TABLE TICKET ADD CONSTRAINT CHECK_PUNTOS_TCKT CHECK(PUNTOS >= 0);
ALTER TABLE TICKET ADD CONSTRAINT CHECK_TOTAL_TCKT CHECK(TOTAL >= 0);