--TODOS LOS PRODUCTOS 
--V_PRODUCTOS
create or replace view v_productos as(
SELECT P.CODIGO_BARRAS "CODIGO DE BARRAS", P.DESCRIPCION, P.PRECIO_ACTUAL "PRECIO CON IVA", I.PORCENTAJE "IVA",  C.NOMBRE_CATEGORIA "CATEGORIA"
FROM PRODUCTO P JOIN CATEGORIA C ON P.CATEGORIA = C.ID
JOIN IVA I ON C.IVA = I.TIPO_IVA);

--SOLO PRODUCTOS EN OFERTA
--V_PRODUCTOS_OFERTA

create or replace view v_productos_oferta as(
SELECT P.CODIGO_BARRAS "CODIGO DE BARRAS", P.DESCRIPCION, P.PRECIO_ACTUAL "PRECIO CON IVA", I.PORCENTAJE "IVA",  C.NOMBRE_CATEGORIA "CATEGORIA", O.TIPO_OFERTA
FROM PRODUCTO P JOIN CATEGORIA C ON P.CATEGORIA = C.ID
JOIN IVA I ON C.IVA = I.TIPO_IVA
JOIN OFERTA O ON P.OFERTA = O.ID);

--IDENTIFICACIÓN DE PRODUCTOS POR PROVEEDOR
--V_PROVEEDOR_PRODUCTOS

create or replace view V_PROVEEDOR_PRODUCTOS as(
SELECT P.CODIGO_BARRAS, P.DESCRIPCION, R.NOMBRE_PROVEEDOR, R.RESPONSABLE_EMPRESA, R.TELEFONO
FROM PRODUCTO P JOIN PROVEE PE ON P.CODIGO_BARRAS = PE.PRODUCTO
JOIN PROVEEDOR R ON PE.PROVEEDOR = R.ID);


--V_REPONEDORES ¡¡¡PARA EL SUPERVISOR Y EL DIRE!!!!!
CREATE OR REPLACE VIEW V_REPONEDORES AS(
SELECT E.NOMBRE ||' '|| E.APELLIDO1 ||' '|| E.APELLIDO2 "EMPLEADO", P.DESCRIPCION "PASILLO ASIGNADO", C.NOMBRE_CARGO "CARGO"
FROM EMPLEADO E JOIN REPONE R ON E.ID = R.EMPLEADO
JOIN PASILLO P ON R.PASILLO = P.ID
JOIN CAT_EMPLEADO C ON E.CAT_EMPLEADO = C.ID);

--V_SUPERVISORES ¡¡PARA EL SUPER Y EL DIRE!!!
CREATE OR REPLACE VIEW V_SUPERVISORES AS(
SELECT E.NOMBRE ||' '|| E.APELLIDO1 ||' '|| E.APELLIDO2 "EMPLEADO",'EQUIPO NUMERO '|| Q.ID ||' MARCA '||
UPPER(Q.MARCA) ||' MODELO '|| UPPER(Q.MODELO) ||' DE TIPO '|| UPPER(Q.TIPO_EQUIPO) "EQUIPO"
FROM EMPLEADO E JOIN SUPERVISA S ON S.EMPLEADO = E.ID
JOIN EQUIPO Q ON S.EQUIPO = Q.ID);


--V_EMPLEADOS ¡¡¡¡SOLO PARA EL DIRE!!!!
CREATE OR REPLACE VIEW V_EMPLEADOS AS(
SELECT E.NOMBRE ||' '|| E.APELLIDO1 ||' '|| E.APELLIDO2 "EMPLEADO", E.ID "CODIGO",  C.NOMBRE_CARGO "CARGO"
FROM EMPLEADO E JOIN CAT_EMPLEADO C ON E.CAT_EMPLEADO = C.ID);

--V_CLIENTES_FIDELIZADOS  ¡¡¡SOLO PARA EL DIRECTOR!!!
CREATE OR REPLACE VIEW V_CLIENTES_FIDELIZADOS AS(
SELECT C.NOMBRE ||' '|| C.APELLIDO1 ||' '|| C.APELLIDO2 "CLIENTE", F.NUM_CLIENTE "NUMERO CLIENTE", F.N_TARJETA "TARJETA", F.PUNTOS_ACUMULADOS "PUNTOS"
FROM CLIENTE C JOIN FIDELIZADO F ON C.DNI = F.DNI);


--V_CORREO_EMPLEADOS
CREATE OR REPLACE VIEW V_CORREO_EMPLEADOS AS(
SELECT NOMBRE || ' ' || APELLIDO1 || ' ' || APELLIDO2 "EMPLEADO", EMAIL FROM EMPLEADO);

--GRANTS VISTAS DEL DIRECTOR
grant select on v_reponedores to r_director;
grant select on V_SUPERVISORES to r_director;
grant select on V_EMPLEADOS to r_director;
grant select on V_CLIENTES_FIDELIZADOS to r_director;
grant select on V_PROVEEDOR_PRODUCTOS to r_director;

--GRANTS VISTAS DEL SUPERVISOR
GRANT SELECT ON V_REPONEDORES TO R_SUPERVISOR;
GRANT SELECT ON V_SUPERVISORES TO R_SUPERVISOR;
GRANT SELECT ON V_PRODUCTOS TO R_SUPERVISOR;
GRANT SELECT ON V_PRODUCTOS_OFERTA TO R_SUPERVISOR;
GRANT SELECT ON V_PROVEEDOR_PRODUCTOS TO R_SUPERVISOR;

--GRANTS VISTAS DEL EMPLEADO
GRANT SELECT ON V_CORREO_EMPLEADOS TO R_CAJERO;
GRANT SELECT ON V_PRODUCTOS TO R_CAJERO;
GRANT SELECT ON V_PRODUCTOS_OFERTA TO R_CAJERO;
